; mandb.

(import :datetime)
(import :man (.resolve $paren-home "tools"))

(function make-index (file)
  ;; page [', ' page] ... ' - ' one-line-desc
  (with-open ($in file :read)
    (if (! (prefix? (read-line) "# NAME")) (raise ArgumentError "illegal manual file")
        (return `(,@(man-parse-one-line-desc (read-line)) ,(.to-s (.relativize $man-root file)))))))

(function make-indexes (dir)
  ;; indexes = section-index ...
  ;; section-index = (section file-index ...)
  ;; file-index = ((page ...) one-line-desc file-name)
  (let (indexes nil)
    (dolist (file (.children dir))
      (if (man-file? file) (push! (make-index file) indexes)))
    (cons (man-dir->section dir) (sort! indexes :key caar))))

(function! main (args)
  (with-open ($out $man-indexes :write)
    (write-line "; indexes for man.")
    (write-line ";; The following indexes were automatically generated by mandb(1).")
    (dolist (dir (.children $man-root))
      (if (man-dir? dir) (write (make-indexes dir))))))
