name: mandb
on: [push]
jobs:
  mandb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make os=unix
        working-directory: ./src
      - run: ./paren mandb
      - run: git add .
      - run: git commit -m "Update by GitHub Action"
      - run: git push
