name: unit-test
on: [push]
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make os=unix debug=on
        working-directory: ./src
      - run: |
          ./paren manutg
          ./paren unit-test ./wk
