name: unit-test
on: [push]
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make os=unix debug=on
        working-directory: ./src
      - run: ./paren manutg
      - run: ../paren unit-test
        working-directory: ./wk
